# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('suggested', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=0)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('medical', models.PositiveSmallIntegerField(default=10)),
                ('casual', models.PositiveSmallIntegerField(default=8)),
                ('earned', models.PositiveSmallIntegerField(default=3)),
                ('study', models.PositiveSmallIntegerField(default=15)),
                ('holiday', models.PositiveSmallIntegerField(default=3)),
                ('faculty', models.BooleanField(default=0)),
                ('hod', models.BooleanField(default=0)),
                ('registrar', models.BooleanField(default=0)),
                ('director', models.BooleanField(default=0)),
                ('work_holiday', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
