# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161010_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_status',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to=settings.AUTH_USER_MODEL),
        ),
    ]
