# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leave_status',
            name='userid',
        ),
        migrations.AddField(
            model_name='leave_status',
            name='user',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
