# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161012_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_status',
            name='user',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL),
        ),
    ]
